-- SELECT *
-- FROM mytable;

-- CREACIÓN DE LA TABLA PELÍCULAS
CREATE TABLE IF NOT EXISTS Peliculas (
	ID INTEGER PRIMARY KEY,
	Titulo TEXT,
	Director TEXT,
	Anio INTEGER,
	Duración INTEGER
)
-- PRIMERA CONSULTA SELECCIONAR TODOS LOS CAMPOS QUE TENGA LA TABLA PELÍCULAS
SELECT * FROM Peliculas 




